[osc-conf]
layout=bottombar
scalewindowed=0.95
scalefullscreen=1.0
hidetimeout=350
fadeduration=100
minmousemove=0
seekbarstyle=bar
seekbarhandlesize=0.6
seekrangestyle=inverted
seekrangeseparate=yes
seekrangealpha=200
timetotal=yes
visibility=auto
boxalpha=80
vidscale=no
deadzonesize=0.85
valign=0.98
halign=0.00
barmargin=0
title=${media-title}
windowcontrols_title=${media-title}
