/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.5-10-g2aefd64d48-20260730"
#endif /* AVUTIL_FFVERSION_H */
