# ==========================================
# 🚀 MOVIEMANAGER DESKTOP - MPV CONFIG
# ==========================================

# ── بافر و حافظه پنهان ──
hwdec=auto-safe
cache=yes
cache-secs=60
demuxer-max-bytes=157286400
demuxer-max-back-bytes=52428800
demuxer-readahead-secs=60

# ── غیرفعال‌سازی خط سفید و OSD زائد ──
osd-bar=no
osc=no
osd-font=Vazirmatn,Segoe UI,Tahoma,Arial
osd-font-size=28

# ── زیرنویس و فونت فارسی ──
sub-auto=fuzzy
sub-font=Vazirmatn,Segoe UI,Tahoma,Arial
sub-font-size=46
sub-border-size=3.0
sub-margin-y=48
sub-ass-override=force
slang=fa,fas,per,en,eng
alang=fa,fas,per,en,eng

# ── پنجره و استایل ──
border=no
keepaspect-window=no
save-position-on-quit=no
autofit=80%
autofit-larger=95%
autofit-smaller=40%

# ── بازیابی اندازه و مکان پنجره و استایل زیرنویس ──
include="~~/window_state.conf"
include="~~/sub_style.conf"
