# Subtitle Customization Config
sub-ass-override=force
sub-font-size=57
sub-scale=1.24
sub-color="#FFFF00"
sub-border-size=4
sub-border-color="#660000"
sub-margin-y=48
sub-bold=yes
sub-box=yes
sub-border-style=background-box
sub-back-color="#BC252525"
